//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab23.DBlab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public int IdR { get; set; }
        public int IdTicket { get; set; }
    
        public virtual PersonTicket PersonTicket { get; set; }
    }
}
